-- MySQL Script generated by MySQL Workbench
-- Wed Sep 18 18:46:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`chambre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chambre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chambre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `etat` VARCHAR(45) NOT NULL,
  `prix` DECIMAL(6,2) NOT NULL,
  `specialite` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `tel` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`service` ;

CREATE TABLE IF NOT EXISTS `mydb`.`service` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `horaire` DATETIME NOT NULL,
  `tarif` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paiement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`paiement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`paiement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cout` DECIMAL(6,2) NOT NULL,
  `methode_paiement` VARCHAR(45) NOT NULL,
  `statut_paiement` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reservation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_arrivee` DATE NOT NULL,
  `date_depart` DATE NOT NULL,
  `nbre_personnes` INT NOT NULL,
  `preferences` VARCHAR(45) NOT NULL,
  `statut` VARCHAR(45) NOT NULL,
  `chambre_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  `paiement_id` INT NOT NULL,
  PRIMARY KEY (`id`, `chambre_id`, `client_id`, `service_id`, `paiement_id`),
  INDEX `fk_reservation_chambre_idx` (`chambre_id` ASC) VISIBLE,
  INDEX `fk_reservation_client1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_reservation_service1_idx` (`service_id` ASC) VISIBLE,
  INDEX `fk_reservation_paiement1_idx` (`paiement_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_chambre`
    FOREIGN KEY (`chambre_id`)
    REFERENCES `mydb`.`chambre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_service1`
    FOREIGN KEY (`service_id`)
    REFERENCES `mydb`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_paiement1`
    FOREIGN KEY (`paiement_id`)
    REFERENCES `mydb`.`paiement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`feedback` ;

CREATE TABLE IF NOT EXISTS `mydb`.`feedback` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `note` INT NOT NULL,
  `commentaire` MEDIUMTEXT NOT NULL,
  `date` DATE NOT NULL,
  `reservation_id` INT NOT NULL,
  `reservation_chambre_id` INT NOT NULL,
  `reservation_client_id` INT NOT NULL,
  `reservation_service_id` INT NOT NULL,
  `reservation_paiement_id` INT NOT NULL,
  PRIMARY KEY (`id`, `reservation_id`, `reservation_chambre_id`, `reservation_client_id`, `reservation_service_id`, `reservation_paiement_id`),
  INDEX `fk_feedback_reservation1_idx` (`reservation_id` ASC, `reservation_chambre_id` ASC, `reservation_client_id` ASC, `reservation_service_id` ASC, `reservation_paiement_id` ASC) VISIBLE,
  CONSTRAINT `fk_feedback_reservation1`
    FOREIGN KEY (`reservation_id` , `reservation_chambre_id` , `reservation_client_id` , `reservation_service_id` , `reservation_paiement_id`)
    REFERENCES `mydb`.`reservation` (`id` , `chambre_id` , `client_id` , `service_id` , `paiement_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;






SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
